#!/usr/bin/env python
Import('env')

env_drivers = env.Clone()

env.drivers_sources=[]
#env.add_source_files(env.drivers_sources,"*.cpp")
env_drivers.Append(CPPPATH=["vorbis"])

Export('env_drivers')

SConscript('unix/SCsub');
SConscript('alsa/SCsub');
SConscript('pulseaudio/SCsub');
SConscript('windows/SCsub');
SConscript('gles2/SCsub');
SConscript('gl_context/SCsub');
SConscript('pnm/SCsub');
SConscript('3ds/SCsub');

if (env['openssl']!='no'):
	env_drivers.Append(CPPFLAGS=['-DOPENSSL_ENABLED']);
	if (env['openssl']=="builtin"):
		env_drivers.Append(CPPPATH=['#drivers/builtin_openssl2'])
		SConscript("builtin_openssl2/SCsub");

Import('env')

env.drivers_sources = []

if ("builtin_zlib" in env and env["builtin_zlib"] == "yes"):
    SConscript("zlib/SCsub")

# OS drivers
SConscript('unix/SCsub')
SConscript('windows/SCsub')

# Sounds drivers
SConscript('alsa/SCsub')
SConscript('pulseaudio/SCsub')
if (env["platform"] == "windows"):
    SConscript("rtaudio/SCsub")

# Graphics drivers
SConscript('gles2/SCsub')
SConscript('gl_context/SCsub')

# Core dependencies
SConscript("png/SCsub")
SConscript("nrex/SCsub")

# Tools override
# FIXME: Should likely be integrated in the tools/ codebase
if (env["tools"] == "yes"):
    SConscript("convex_decomp/SCsub")

if env['vsproj'] == "yes":
    env.AddToVSProject(env.drivers_sources)

if env.split_drivers:
    env.split_lib("drivers")
else:
    env.add_source_files(env.drivers_sources, "*.cpp")
    lib = env.Library("drivers", env.drivers_sources)
    env.Prepend(LIBS=[lib])
